on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v14
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: install
      run: yarn install

    - name: eslint
      run: yarn lint

    - name: Update version in package.json (Release only)
      if: github.event_name == 'release'
      run: yarn version --new-version $(echo ${{ github.event.release.tag_name }} | sed -e "s/v//gI") --no-git-tag-version

    - name: build
      run: yarn build

    - name: build typedoc (Release only)
      if: github.event_name == 'release'
      run: yarn run doc

    - name: Publish typedoc (Release only)
      if: github.event_name == 'release'
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: build/docs/

    - name: Publish to npmjs.org (Release only)
      if: github.event_name == 'release'
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_LEON_ACCESS_TOKEN }}
        package: ./node/package.json
